<select size="1" name="Destination-Sofia" class="search_sofia" tabindex="5">
<option value=""><b>София</b></option>
<option value="1">Абдовица</option>
<option value="2">Аерогарата</option>
<option value="3">Балша</option>
<option value="4">Банишора</option>
<option value="5">Банкя</option>
<option value="6">Белите Брези</option>
<option value="7">Беловодски Път в.з.</option>
<option value="8">Бенковски</option>
<option value="9">Бистрица</option>
<option value="10">Бокар</option>
<option value="11">Борово</option>
<option value="12">Ботевграско шосе</option>
<option value="13">Ботунец</option>
<option value="14">Бояна</option>
<option value="15">Бункера в.з.</option>
<option value="16">Бусманци</option>
<option value="17">Бухово</option>
<option value="18">Бъкстон</option>
<option value="19">Витоша</option>
<option value="20">Владая</option>
<option value="21">Военна Рампа</option>
<option value="22">Войнеговци</option>
<option value="23">Волуяк</option>
<option value="24">Враждебна</option>
<option value="25">Враня</option>
<option value="26">Връбница 1</option>
<option value="27">Връбница 2</option>
<option value="28">Гара Искър</option>
<option value="29">Гевгелийски</option>
<option value="30">Гео Милев</option>
<option value="31">Герман</option>
<option value="32">Гниляне</option>
<option value="33">Горна Баня</option>
<option value="34">Горни Богров</option>
<option value="35">Горубляне</option>
<option value="36">Гоце Делчев</option>
<option value="37">Дианабад</option>
<option value="38">Димитър Миленков</option>
<option value="39">Доброславци</option>
<option value="40">Долни Богров</option>
<option value="41">Долни Пасарел</option>
<option value="42">Драгалевци</option>
<option value="43">Дружба</option>
<option value="44">Дружба 1</option>
<option value="45">Дружба 2</option>
<option value="46">Дървеница</option>
<option value="47">Железница</option>
<option value="48">Желява</option>
<option value="49">Житен</option>
<option value="50">Западен Парк</option>
<option value="51">Захарна Фабрика</option>
<option value="52">Зона Б18</option>
<option value="53">Зона Б19</option>
<option value="54">Зона Б5</option>
<option value="55">Иван Вазов</option>
<option value="56">Иваняне</option>
<option value="57">Изгрев</option>
<option value="58">Изток</option>
<option value="59">Илинден</option>
<option value="60">Илиянци</option>
<option value="61">Казичене</option>
<option value="62">Камбаните</option>
<option value="63">Карпузица</option>
<option value="64">Килиите в.з.</option>
<option value="65">Киноцентър в.з.</option>
<option value="66">Клисура</option>
<option value="67">Княжево</option>
<option value="68">Кокаляне</option>
<option value="69">Красна Поляна</option>
<option value="70">Красно Село</option>
<option value="71">Кремиковци</option>
<option value="72">Крива Река</option>
<option value="73">Кривина</option>
<option value="74">Кръстова Вада</option>
<option value="75">Кубратово</option>
<option value="76">Кътина</option>
<option value="78">Лагера</option>
<option value="79">Левски</option>
<option value="80">Левски В</option>
<option value="81">Левски Г</option>
<option value="82">Лозен</option>
<option value="83">Лозенец</option>
<option value="84">Локорско</option>
<option value="85">Ломско шосе</option>
<option value="86">Люлин 1</option>
<option value="87">Люлин 10</option>
<option value="88">Люлин 2</option>
<option value="89">Люлин 3</option>
<option value="90">Люлин 4</option>
<option value="91">Люлин 5</option>
<option value="92">Люлин 6</option>
<option value="93">Люлин 7</option>
<option value="94">Люлин 8</option>
<option value="95">Люлин 9</option>
<option value="96">Люлин Център</option>
<option value="97">Малашевци</option>
<option value="98">Малинова Долина</option>
<option value="99">Мало Бучино</option>
<option value="100">Манастирски Ливади</option>
<option value="101">Мировяне</option>
<option value="102">Младост 1</option>
<option value="103">Младост 1а</option>
<option value="104">Младост 2</option>
<option value="105">Младост 3</option>
<option value="106">Младост 4</option>
<option value="107">Модерно Предградие</option>
<option value="108">Мотописта</option>
<option value="109">Мрамор</option>
<option value="110">Мусагеница</option>
<option value="111">Мърчаево</option>
<option value="112">Надежда 1</option>
<option value="113">Надежда 2</option>
<option value="114">Надежда 3</option>
<option value="115">Надежда 4</option>
<option value="116">Надежда 5</option>
<option value="117">Надежда 6</option>
<option value="118">Негован</option>
<option value="119">Нови Искър</option>
<option value="120">Обеля</option>
<option value="121">Обеля 1</option>
<option value="122">Обеля 2</option>
<option value="123">Оборище</option>
<option value="124">Овча Купел</option>
<option value="125">Овча Купел 1</option>
<option value="126">Овча Купел 2</option>
<option value="127">Околовръстен Път</option>
<option value="128">Орландовци</option>
<option value="130">Павлово</option>
<option value="131">Панчарево</option>
<option value="132">Пасарел</option>
<option value="133">Пирогов</option>
<option value="134">Плана</option>
<option value="135">Планина Витоша</option>
<option value="136">Подгумер</option>
<option value="137">Подуене</option>
<option value="138">Полигона</option>
<option value="139">Разсадника</option>
<option value="140">Редута</option>
<option value="141">Република</option>
<option value="142">Света Троица</option>
<option value="143">Световрачене</option>
<option value="144">Свобода</option>
<option value="145">Сердика</option>
<option value="146">Сеславци</option>
<option value="147">Симеоново</option>
<option value="148">Ситняково</option>
<option value="149">Славия</option>
<option value="150">Слатина</option>
<option value="151">Стефан Караджа</option>
<option value="152">Стрелбище</option>
<option value="153">Студентски Град</option>
<option value="154">Суха Река</option>
<option value="156">Суходол</option>
<option value="157">Толстой</option>
<option value="158">Требич</option>
<option value="159">Триъгълника</option>
<option value="160">Факултета</option>
<option value="161">Филиповци</option>
<option value="162">Фондови Жилища</option>
<option value="163">Хаджи Димитър</option>
<option value="164">Хиподрума</option>
<option value="165">Хладилника</option>
<option value="166">Христо Ботев</option>
<option value="167">Цариградски комплекс</option>
<option value="168">Цариградско Шосе</option>
<option value="169">Централна гара</option>
<option value="170">Център</option>
<option value="171">Чeлопечене</option>
<option value="172">Чепинци</option>
<option value="173">Яворов</option>
<option value="174">Яна</option>
</select>
